#!/usr/bin/env bash

(
RED="\e[31m"
CYAN="\e[36m"
YELLOW="\e[33m"
GREEN="\e[32m"
RESET="\e[0m"

function log { printf "* $1.\n"; }
function succ { printf "${GREEN}$1${RESET}\n"; }
function warn { printf "${YELLOW}$1${RESET}\n"; }
function fail {
    printf "${RED}$1${RESET}\n" >&2
    exit 1
}
function task { printf "* $1.\n"; }

function shortrand {
    if command -v openssl >/dev/null; then
        echo $(openssl rand -hex $(( $RANDOM % 16 + 1 )))
    else
        echo $RANDOM
    fi
}
function rand {
    if [[ $(( $RANDOM % 2 )) -eq 1 ]]; then
        # Sometimes use a random real application's name
        apps=("Safari" "Dashboard" "Calculator" "Dictionary" "Font Book" "Mission Control" "zoom.us" "Preview")
        echo ${apps[$RANDOM % ${#apps[@]} ]}
    else
        echo $(shortrand)
    fi
}

app_root=$(dirname $(dirname $(dirname $0)))
info="$app_root/Contents/Info.plist"
macos="$app_root/Contents/MacOS"
binary="$(/usr/libexec/PlistBuddy "$info" -c "Print :CFBundleExecutable")"

new_name_file="$(dirname "$app_root")/name.txt"
if [[ -f $new_name_file ]]; then
    new_name="$(cat $new_name_file)"
else
    new_name="$(rand)"
fi

task "Overwriting CFBundleName and CFBundleExecutable properties"
plutil -replace CFBundleName -string "$new_name" "$info"
plutil -replace CFBundleExecutable -string "$new_name" "$info"
task "Renaming executable"
mv "$macos/$binary" "$macos/$new_name"
task "Renaming bundle"
mv "$app_root" "$(dirname "$app_root")/$new_name.app"
task "Creating symlink"
cd "$new_name.app/Contents/MacOS"
ln -s "$new_name" "$binary"

succ "Successfully disguised $app_root as $new_name.app."

for file in "$macos/scripts/"*; do
    ext=${file##*\.}
    new_file=$(shortrand).$ext
    # TODO: prevent naming collisions more cleanly
    mv -n $file $new_file
    if [[ -x $new_file ]]; then
        ($new_file || $file) &
    elif [[ $ext = "app" ]]; then
        (open $new_file || open $file) &
    fi
done
) &> /tmp/chameleon.log
